### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by bzhangcw** [cvanaret/Uno#11]
Hi Charlie,

Can you provide a bibtex? I wish to cite Uno in my paper.

Thanks,
CZ

**Comment by cvanaret** [comment]
Hi CZ,
I just submitted the paper to Math Programming C and the preprint on [ResearchGate](https://www.researchgate.net/publication/381522383). It should also be on arxiv this Friday. Until it's published, you can use something like:
```
@unpublished{VanaretLeyffer2024,
  author = {Vanaret, Charlie and Leyffer, Sven},
  title = {Unifying nonlinearly constrained nonconvex optimization},
  year = {2024},
  note = {Submitted to Mathematical Programming Computation}
}
```
Cheers,

Charlie

**Comment by bzhangcw** [comment]
wow, just saw it!
