### ISSUE TITLE
dl should not be a required library on Windows

### ISSUE THREAD

**Issue by amontoison** [cvanaret/Uno#21]
`libdl` doesn't exist on Windows (to the best of my knowledge)
https://github.com/cvanaret/Uno/blob/main/CMakeLists.txt#L149-L150

**Comment by traversaro** [comment]
Indeed it seems that `dlfcn.h` is not used, so it make sense to remove this. Anyhow, just if someone finds this issue on github, there is a `dl` implementation for Windows at https://github.com/dlfcn-win32/dlfcn-win32 .

**Comment by cvanaret** [comment]
I now use `CMAKE_DL_LIBS` instead of looking for the dl library (and only for the `uno_ampl` target).
This should be fixed in commit 3bd2244.

**Comment by amontoison** [comment]
Thanks @cvanaret, it fixed the issue on Windows :+1: 
Can you also add the compilation flag `-fPIC` by default when you compile Uno please?
I can "transform" a `libuno.a` into a `libuno.$dlext` with this option.

**Comment by cvanaret** [comment]
> Can you also add the compilation flag `-fPIC` by default when you compile Uno please? I can "transform" a `libuno.a` into a `libuno.$dlext` with this option.

Introduced in commit 0513043 :)
