### ISSUE TITLE
Document options

### ISSUE THREAD

**Issue by odow** [cvanaret/Uno#26]
For example, what values can these take:

https://github.com/cvanaret/Uno/blob/1f373ce25049e593088bee66b37a9057039ac19a/uno.options#L94-L102

**Comment by odow** [comment]
To answer my own question, currently they are the only options:
https://github.com/cvanaret/Uno/blob/1f373ce25049e593088bee66b37a9057039ac19a/uno/solvers/QPSolverFactory.hpp#L21-L28
https://github.com/cvanaret/Uno/blob/1f373ce25049e593088bee66b37a9057039ac19a/uno/solvers/LPSolverFactory.hpp#L20-L26
although `linear_solver` can be MUMPS
https://github.com/cvanaret/Uno/blob/1f373ce25049e593088bee66b37a9057039ac19a/uno/solvers/SymmetricIndefiniteLinearSolverFactory.hpp#L23-L34

**Comment by cvanaret** [comment]
As a partial answer, the following command is available:
```shell
charlie@africa /media/data/Uno/build $ ./uno_ampl --strategies
Available strategies:
Constraint relaxation strategies: feasibility_restoration, l1_relaxation
Globalization mechanisms: TR, LS
Globalization strategies: l1_merit, fletcher_filter_method, waechter_filter_method, funnel_method
Subproblems: QP, LP, primal_dual_interior_point
```
I will add the available subproblem solvers.

**Comment by cvanaret** [comment]
With commit 73fa292, the command `./uno_ampl --strategies` produces (when all subproblem solvers are installed):
```shell
Available strategies:
- Constraint relaxation strategies: feasibility_restoration, l1_relaxation
- Globalization mechanisms: TR, LS
- Globalization strategies: l1_merit, fletcher_filter_method, waechter_filter_method, funnel_method
- Subproblems: QP, LP, primal_dual_interior_point
- QP solvers: BQPD
- LP solvers: BQPD
- Linear solvers: MA57, MUMPS
```
