### ISSUE TITLE
What is the motivation for ignoring integrality in models

### ISSUE THREAD

**Issue by odow** [cvanaret/Uno#30]
If the user passes a MINLP, shouldn't you error instead of solving the relaxation? I can see this causing a bunch of issues once people start using Uno. IIRC, Ipopt does the same thing. But that does't mean it was a good choice.

https://github.com/cvanaret/Uno/blob/1f373ce25049e593088bee66b37a9057039ac19a/bindings/AMPL/AMPLModel.cpp#L21-L22

**Comment by cvanaret** [comment]
Yes, I will replace the warning with an error.

**Comment by cvanaret** [comment]
Implemented in commit 123c422.
