### ISSUE TITLE
Use of HSL linear solvers in Uno

### ISSUE THREAD

**Issue by amontoison** [cvanaret/Uno#44]
I suggest to split the detection of libraries related to HSL linear solvers.  
Right now, only MA57 is interfaced, but if more solvers are added, we want something like this:
```shell
if findlibrary(hsl)
  ... # compile all HSL interfaces
else
  if findlibrary(ma57)
    ... # compile the interface for MA57
  endif
  if findlibrary(ma27)
    ... # compile the interface for MA27
  endif
endif
```
This way, we can also determine if we explicitly linked with libHSL, and thus decide whether or not we can use the routine `LIBHSL_isfunctional` to ensure at runtime that HSL solvers are available.
This is particularly relevant for Julia users, where Uno is always compiled with a "dummy" version of libHSL.
It allows them to easily switch to the HSL solvers if they can install the official libHSL (like academic users) with `HSL_jll.jl`.

**Comment by cvanaret** [comment]
Implemented in commit 20e0b2c.
