### ISSUE TITLE
Write the bound duals in the AMPL solution using suffixes

### ISSUE THREAD

**Issue by cvanaret** [cvanaret/Uno#47]
At the moment, the call to ASL's `write_sol_ASL` writes the primal solution and the constraint duals in the .sol file. The bound duals should also be written using suffixes (see [ASL documentation](https://ampl.com/_archive/first-website/REFS/hooking3.pdf) pp 20-22).
Reported by @odow.

**Comment by cvanaret** [comment]
Implemented in commit dd77f37.
The suffixes are `lower_bound_duals` and `upper_bound_duals`.

**Comment by odow** [comment]
Nice!

Currently, we've got these strings hard-coded into MOI:
https://github.com/jump-dev/MathOptInterface.jl/blob/ee313beac6e9853fe1ae3bab79befa0f51a27886/src/FileFormats/NL/sol.jl#L348-L364

So I guess we should make the sol reader more flexible as to how it parses suffixes.

Alternatively, we could make Uno call them `ipopt_zL_out` and `ipopt_zU_out`... but I don't know if that is a good or bad idea. I agree that the suffix stuff in ASL is horrible.

**Comment by cvanaret** [comment]
Making the sol reader more flexible would be advantageous, although I'm unsure which convention we could use.
Using the IPOPT suffixes in Uno would be a bit weird. Would it be an option - as a quick fix - to add a command line in ~Uno_jll's `build_tarballs.jl`~ the definition of `Uno_jll.amplexe` to replace Uno's suffixes with IPOPT's suffixes in the .sol file?

**Comment by odow** [comment]
I'll fix this in MOI https://github.com/jump-dev/MathOptInterface.jl/issues/2566
