### ISSUE TITLE
Build and test uno_ampl in CI

### ISSUE THREAD

**Issue by odow** [cvanaret/Uno#48]
So it occured to me that if we built uno_ampl in CI, then we could install Julia and run our full suite of tests in your CI, rather than waiting for the Uno_jll round trip. This would give you instant access to a pretty large and varied test suite.

From what I can tell though, we don't currently build uno_ampl in CI because of the BQPD/MUMPS requirements?

**Comment by cvanaret** [comment]
It would be totally doable to download the ASL and MUMPS sources from given links, compile them, then compile uno_ampl.
I'll have a look when I have a moment.
